name: Deploy API to Staging

on:
  push:
    branches: [main, staging]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api-staging.yml'
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'api/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Install Serverless Framework
        run: npm install -g serverless
        working-directory: ./api

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get SSM Parameters
        run: |
          echo "SERVERLESS_LICENSE_KEY=$(aws ssm get-parameter --name "/digidinez/common/SERVERLESS_LICENSE_KEY" --with-decryption --query "Parameter.Value" --output text --region ap-south-1)" >> $GITHUB_ENV

      - name: Deploy to AWS
        run: serverless deploy --stage staging
        working-directory: ./api

      - name: Deployment complete
        run: echo "API deployed to staging-api.digidinez.com"